namespace NPA.Core.Annotations;

/// <summary>
/// Defines the strategies for generating primary key values.
/// </summary>
public enum GenerationType
{
    /// <summary>
    /// The primary key is generated by the database using auto-increment or identity columns.
    /// </summary>
    Identity,

    /// <summary>
    /// The primary key is generated using a database sequence.
    /// </summary>
    Sequence,

    /// <summary>
    /// The primary key is generated using a table-based generator.
    /// </summary>
    Table,

    /// <summary>
    /// No automatic generation. The primary key must be manually assigned.
    /// </summary>
    None
}
