namespace NPA.Core.Annotations;

/// <summary>
/// Indicates that a method should be automatically generated by the source generator.
/// This attribute can control the generation behavior and provide hints to the generator.
/// </summary>
/// <example>
/// <code>
/// [GeneratedMethod(IncludeNullCheck = true, GenerateAsync = true)]
/// User? FindByUsername(string username);
/// 
/// [GeneratedMethod(CustomSql = "SELECT * FROM users WHERE id = @id")]
/// User? GetById(int id);
/// </code>
/// </example>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
public sealed class GeneratedMethodAttribute : Attribute
{
    /// <summary>
    /// Gets or sets whether to include null parameter checks in the generated method.
    /// Default is true.
    /// </summary>
    public bool IncludeNullCheck { get; set; } = true;

    /// <summary>
    /// Gets or sets whether to automatically generate an async version of this method.
    /// Default is false.
    /// </summary>
    public bool GenerateAsync { get; set; }

    /// <summary>
    /// Gets or sets whether to generate a sync version of this async method.
    /// Default is false.
    /// </summary>
    public bool GenerateSync { get; set; }

    /// <summary>
    /// Gets or sets custom SQL to use for this method.
    /// If specified, this overrides the convention-based SQL generation.
    /// </summary>
    public string? CustomSql { get; set; }

    /// <summary>
    /// Gets or sets whether to include logging in the generated method.
    /// Default is false.
    /// </summary>
    public bool IncludeLogging { get; set; }

    /// <summary>
    /// Gets or sets whether to wrap the method in a try-catch block.
    /// Default is false.
    /// </summary>
    public bool IncludeErrorHandling { get; set; }

    /// <summary>
    /// Gets or sets a description for the generated method.
    /// This will be included in XML documentation.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="GeneratedMethodAttribute"/> class.
    /// </summary>
    public GeneratedMethodAttribute()
    {
    }
}
