using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using NPA.Design.Models;
using NPA.Design.Generators.Helpers;

namespace NPA.Design.Generators.CodeGenerators;

/// <summary>
/// Generates the main repository class structure.
/// </summary>
internal static class RepositoryCodeGenerator
{
    /// <summary>
    /// Generates the repository class header (file header, using statements, namespace, class declaration, and constructor).
    /// </summary>
    public static string GenerateRepositoryHeader(RepositoryInfo info)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This code was generated by NPA.Design.RepositoryGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Dapper;");
        sb.AppendLine("using NPA.Core.Core;");
        sb.AppendLine("using NPA.Core.Repositories;");
        sb.AppendLine("using NPA.Core.Metadata;");

        // Add multi-tenancy using if needed
        if (info.MultiTenantInfo?.IsMultiTenant == true)
        {
            sb.AppendLine("using NPA.Core.MultiTenancy;");
        }

        sb.AppendLine();

        sb.AppendLine($"namespace {info.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Generated implementation of {info.InterfaceName}.");

        // Add multi-tenant documentation if applicable
        if (info.MultiTenantInfo?.IsMultiTenant == true)
        {
            sb.AppendLine($"    /// This repository supports multi-tenancy with automatic tenant filtering.");
            sb.AppendLine($"    /// Tenant property: {info.MultiTenantInfo.TenantIdProperty}");
            if (info.MultiTenantInfo.AllowCrossTenantQueries)
            {
                sb.AppendLine($"    /// Cross-tenant queries: Allowed (use WithoutTenantFilterAsync for admin operations)");
            }
            else
            {
                sb.AppendLine($"    /// Cross-tenant queries: Not allowed");
            }
        }

        sb.AppendLine($"    /// </summary>");

        // Build the interface list - add Partial interface if relationships exist
        // Use unqualified names since the class is in the same namespace as the interfaces
        var interfaces = info.InterfaceName;
        if (info.Relationships.Count > 0)
        {
            var partialInterfaceName = info.InterfaceName + "Partial";
            interfaces = $"{info.InterfaceName}, {partialInterfaceName}";
        }

        sb.AppendLine($"    public class {StringHelper.GetImplementationName(info.InterfaceName)} : BaseRepository<{info.EntityType}, {info.KeyType}>, {interfaces}");
        sb.AppendLine("    {");

        // Generate constructor
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Initializes a new instance of the {StringHelper.GetImplementationName(info.InterfaceName)} class.");
        sb.AppendLine($"        /// </summary>");

        if (info.MultiTenantInfo?.IsMultiTenant == true)
        {
            // Constructor with ITenantProvider
            sb.AppendLine("        public " + StringHelper.GetImplementationName(info.InterfaceName) + "(IDbConnection connection, IEntityManager entityManager, IMetadataProvider metadataProvider, ITenantProvider? tenantProvider = null)");
            sb.AppendLine("            : base(connection, entityManager, metadataProvider, tenantProvider)");
        }
        else
        {
            // Constructor without ITenantProvider
            sb.AppendLine("        public " + StringHelper.GetImplementationName(info.InterfaceName) + "(IDbConnection connection, IEntityManager entityManager, IMetadataProvider metadataProvider)");
            sb.AppendLine("            : base(connection, entityManager, metadataProvider)");
        }

        sb.AppendLine("        {");
        sb.AppendLine("        }");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Generates the repository class footer (closing braces).
    /// </summary>
    public static string GenerateRepositoryFooter()
    {
        var sb = new StringBuilder();
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Generates the service collection extension for dependency injection.
    /// </summary>
    public static string GenerateServiceCollectionExtension(ImmutableArray<RepositoryInfo> repositories)
    {
        if (repositories.IsEmpty)
            return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This code was generated by NPA.Design.RepositoryGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using NPA.Core.Core;");
        sb.AppendLine("using NPA.Core.Repositories;");
        sb.AppendLine();

        // Add namespaces from all repositories
        var namespaces = repositories.Select(r => r.Namespace).Distinct().OrderBy(n => n);
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Service collection extensions for NPA repositories.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class NPAServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds all NPA-generated repositories to the service collection.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection.</param>");
        sb.AppendLine("    /// <returns>The service collection for chaining.</returns>");
        sb.AppendLine("    public static IServiceCollection AddNPA(this IServiceCollection services)");
        sb.AppendLine("    {");

        // Register EntityManager and BaseRepository
        sb.AppendLine("        // Register core NPA services");
        sb.AppendLine("        services.AddScoped<IEntityManager, EntityManager>();");
        sb.AppendLine();
        sb.AppendLine("        // Register all generated repositories");

        foreach (var repo in repositories.OrderBy(r => r.InterfaceName))
        {
            var implName = StringHelper.GetImplementationName(repo.InterfaceName);
            sb.AppendLine($"        services.AddScoped<{repo.InterfaceName}, {implName}>();");
        }

        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

