namespace NPA.CLI.Templates;

/// <summary>
/// Template for generating repository implementations.
/// </summary>
public class RepositoryImplementationTemplate
{
    public string Generate(string entityName, string namespaceName)
    {
        return $@"using NPA.Core;
using {namespaceName.Replace(".Repositories", ".Entities")};

namespace {namespaceName};

/// <summary>
/// Repository implementation for {entityName} entity.
/// Generated by NPA CLI - implement custom methods here.
/// </summary>
public partial class {entityName}Repository : I{entityName}Repository
{{
    private readonly IEntityManager _entityManager;

    public {entityName}Repository(IEntityManager entityManager)
    {{
        _entityManager = entityManager;
    }}

    // Implement custom query methods here
    // Example:
    // public async Task<{entityName}?> FindByNameAsync(string name)
    // {{
    //     return await _entityManager.CreateQuery<{entityName}>()
    //         .Where(e => e.Name == name)
    //         .FirstOrDefaultAsync();
    // }}
}}
";
    }
}
